name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  code-review:
      uses: step-security/reusable-workflows/.github/workflows/claude_review.yml@fix/claude
      secrets:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
      
permissions:
  contents: read
  pull-requests: write
  packages: read
  issues: write
  id-token: write